### ISSUE TITLE
ImportError: cannot import name 'FileWriter' from 'tensorboard' 

### ISSUE THREAD

**Issue by hkuyam008** [hanzhanggit/StackGAN-Pytorch#16]
I am getting the following error trace while trying to run the Stage I of training using coco dataset

Looks like tensorboard V 1.10.0 (which is what I have installed in my virtual env does not have a class called FileWriter???). My Pycharm IDE is also complaining about the same thing

Traceback (most recent call last):
  File "C:/PyCharmProjects/StackGAN-Pytorch/code/main.py", line 19, in <module>
    from trainer import GANTrainer
  File "C:\PyCharmProjects\StackGAN-Pytorch\code\trainer.py", line 24, in <module>
    from tensorboard import FileWriter
ImportError: cannot import name 'FileWriter' from 'tensorboard' (C:\PythonVEnvs\StackGANPyTorch\lib\site-packages\tensorboard\__init__.py)

Process finished with exit code 1

**Comment by AnwarUllahKhan** [comment]
@hkuyam008 I am facing the same problem did you solve that?

**Comment by hkuyam008** [comment]
@AnwarUllahKhan I ended up uninstalling tensorboard and using tensorflow instead and then you have to change the import to " from tensorflow.summary import FileWriter"

While I very much appreciate the effort these guys have put in to provide a RI of Stack-GAN, 1 glaring drawback of their documentation / wiki is the absence of any kind of software version, OS specifics and platform on which they tested this program.....and "version mismatch" is a nightmarish problem of the software world, which unfortunately no one has found an elegant solution to.....till date.

**Comment by AnwarUllahKhan** [comment]
@hkuyam008 I solved the problem by installing tensorboardX....and also change that from tensorboardX import FileWriter, you can also try this

**Comment by hkuyam008** [comment]
@AnwarUllahKhan Thanks for the solution
