### ISSUE TITLE
Is training the model on Bird and Flower dataset straight forward?

### ISSUE THREAD

**Issue by shenkev** [hanzhanggit/StackGAN-Pytorch#4]
Hi Han,

I wanted to train the model on the the Bird and Flower dataset (like in the Tensorflow version). Would it be as straight forward as downloading the datasets and calling main? I'm guessing you haven't tried this yet, any potential pitfalls you see?

**Comment by hanzhanggit** [comment]
Yes, it is straightforward. Please download dataset and prepare .yml files following the Tensorflow version. However, the Pytorch implementation is for reproducing COCO results and its architecture and hyper-parameters are a little different from the Tensorflow implementation.
