### ISSUE TITLE
inception score on coco pretrained model is 8.50526228697

### ISSUE THREAD

**Issue by kracwarlock** [hanzhanggit/StackGAN-Pytorch#6]
@hanzhanggit The readme says

    Our current implementation has a higher inception score(10.62±0.19) than reported in the StackGAN paper

With the provided pre-trained model, I get 8.50526228697. Is the 10+ score for StackGAN v2?

**Comment by hanzhanggit** [comment]
@kracwarlock 
No. The inception score (10.62±0.19) is calculated from the Pytorch model of  stackgan-v1

**Comment by kracwarlock** [comment]
I was unable to get that from the available pre-trained model in the repo. Can you share the evaluation code for the pytorch model?

How many images did you calculate this over and what were the splits?

**Comment by AnwarUllahKhan** [comment]
@kracwarlock @hanzhanggit @taoxugit Please tell me the path details. 

I put my coco train images into data/coco folder so the complete path is "H://StackGAN-Pytorch/data/coco"
and put the preprocessed char-CNN-RNN text embeddings  **training coco**, and saved it to data/coco/train and test folders.... complete path is H://StackGAN-Pytorch/data/coco/train" and H://StackGAN-Pytorch/data/coco/test"
As well as put the preprocessed char-CNN-RNN text embeddings **evaluating coco**, and save it to data folder complete path is H://StackGAN-Pytorch/data/coco/test"

now tell me these paths are ok or not? and where I put the coco val images? Are any other things are needed? 

Strongly waiting for your's response....
thank you very much
