### ISSUE TITLE
Why the text condition input of netD is `mu`？

### ISSUE THREAD

**Issue by coderSkyChen** [hanzhanggit/StackGAN-Pytorch#7]
Hi,
in trainer.py line:180, the text condition that input to netD is 'mu',
i double why it's not 'c_code' which is the text condition for the netG.

And 'mu' only has half information of the text embedding, so i'm a little confused about it.

Waitting for your reply.

Best regards!

**Comment by wanmingHuang** [comment]
From my understanding, I believe 'mu' is a linear transformation of the text embedding (not half) which is used in discriminator, 'c_code' is 'mu' + logvar*eps which is used in generator for diversity 

In one of the implementation of GAN_CLS, generator reads in text embedding and linearly transformed it. In StackGAN's implementation generator reads in 'mu' that has already been linearly transformed from embedding

**Comment by coderSkyChen** [comment]
thanks~
